version: "3.8"

volumes:
  db-data:

networks:
  mynet:
    driver: bridge

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: pedelogo
    ports:
      - "3306:3306"
